#!/usr/bin/env bash
# This bash script creates and configures HAProxy on lb-01 server
# Send traffic to  HAProxy to web-01 and web-02 servers using HAProxy
# Set the load balancing algorithm to round robin
# Automate HAProxy through an init script
# Finally install and configure HAproxy for my load balancing server
sudo apt-get -y update
apt-get -y install haproxy

# edit the configuration file for haproxy
server_config=\
"
frontend  etinosa-frontend
        bind *:80
        mode http
        default_backend etinosa-backend
backend etinosa-backend
        balance roundrobin
        server 358467-web-01 54.167.178.186:80 check
        server 358467-web-02 34.204.81.124:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Ensure HAProxy can start using init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
