#!/usr/bin/env bash
# This script displays a twelve hour clock for a specified duration

time=0

while [ $time -le 12 ]
do
    echo "Hour: $time"
    minute=1
    while [ $minute -le 59 ]
    do
     echo "$minute"
     ((minute++))
    done
    ((hour++))
done
