#!/usr/bin/env bash
# This script displays a twelve hour clock for a specified duration

i=0
while ((i <= 12)); do
	echo "Hour: $i"
	j=1
	while ((j <= 59)); do
		echo $j
		((j+=1))
	done
	((i+=1))
done
